version: '3'

services:
  redis:
    image: redis:7.0
    container_name: redis
    ports:
      - "6379:6379"
    command: bash -c "redis-server --appendonly yes --requirepass db-password"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
