// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0
// source: bibocomic_landingpage.sql

package db

import (
	"context"
)

const biboComic_LandingPage_SaveUserForEarlyAccess = `-- name: BiboComic_LandingPage_SaveUserForEarlyAccess :one
INSERT INTO p_bibocomic.p_users_early_access_signups(email) VALUES ($1) 
RETURNING email
`

func (q *Queries) BiboComic_LandingPage_SaveUserForEarlyAccess(ctx context.Context, email string) (string, error) {
	row := q.db.QueryRowContext(ctx, biboComic_LandingPage_SaveUserForEarlyAccess, email)
	err := row.Scan(&email)
	return email, err
}
