// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	BlockSessionById(ctx context.Context, sessionID uuid.UUID) (SocialhubSession, error)
	BlockSessionFamily(ctx context.Context, email string) (SocialhubSession, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (SocialhubSession, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	FetchAllPosts(ctx context.Context, createdBy string) ([]SocialhubLinkedinScheduledUserPost, error)
	FetchLinkedinURNbyAccountId(ctx context.Context, arg FetchLinkedinURNbyAccountIdParams) (string, error)
	FetchPostsToBePublished(ctx context.Context, limit int32) ([]FetchPostsToBePublishedRow, error)
	FindLinkedInAccountAccessToken(ctx context.Context, arg FindLinkedInAccountAccessTokenParams) (SocialhubLinkedinAccountAccessToken, error)
	FindTwitterAccountAccessToken(ctx context.Context, arg FindTwitterAccountAccessTokenParams) (SocialhubTwitterAccountAccessToken, error)
	GetSession(ctx context.Context, sessionID uuid.UUID) (SocialhubSession, error)
	GetUserDetails(ctx context.Context, arg GetUserDetailsParams) (GetUserDetailsRow, error)
	ResetUserPassword(ctx context.Context, arg ResetUserPasswordParams) (ResetUserPasswordRow, error)
	SaveLinkedinAccessToken(ctx context.Context, arg SaveLinkedinAccessTokenParams) (SaveLinkedinAccessTokenRow, error)
	SaveLinkedinURN(ctx context.Context, arg SaveLinkedinURNParams) (SaveLinkedinURNRow, error)
	SaveTwitterAccessToken(ctx context.Context, arg SaveTwitterAccessTokenParams) (SaveTwitterAccessTokenRow, error)
	ScheduleAUserPostOnLinkedin(ctx context.Context, arg ScheduleAUserPostOnLinkedinParams) (ScheduleAUserPostOnLinkedinRow, error)
	UpdatePostStatus(ctx context.Context, arg UpdatePostStatusParams) (UpdatePostStatusRow, error)
}

var _ Querier = (*Queries)(nil)
