// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	BlockSessionById(ctx context.Context, sessionID uuid.UUID) (Session, error)
	BlockSessionFamily(ctx context.Context, email string) (Session, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	FindLinkedInAccountAccessToken(ctx context.Context, arg FindLinkedInAccountAccessTokenParams) (SocialhubLinkedinAccountAccessToken, error)
	GetSession(ctx context.Context, sessionID uuid.UUID) (Session, error)
	GetUserDetails(ctx context.Context, userEmail string) (GetUserDetailsRow, error)
	LinkedinScheduleUserPost(ctx context.Context, arg LinkedinScheduleUserPostParams) (LinkedinScheduleUserPostRow, error)
	SaveLinkedinAccessToken(ctx context.Context, arg SaveLinkedinAccessTokenParams) (SaveLinkedinAccessTokenRow, error)
	SaveLinkedinURN(ctx context.Context, arg SaveLinkedinURNParams) (SaveLinkedinURNRow, error)
}

var _ Querier = (*Queries)(nil)
